fields:
  image_name : customfield_16941
  url : customfield_16940
  vuln_url_1: customfield_16805
  vuln_url_2: customfield_16924
  vuln_url_3: customfield_16925
  vuln_url_4: customfield_16926
  vuln_url_5: customfield_16927
  environment_name : customfield_16942
  cve_description : customfield_16937
  package_name_or_version : customfield_16930
  epss_score : customfield_16933
  cvss_score : customfield_16932
  cve_number : customfield_16931
  vulnerability_id_1: customfield_16805
  vulnerability_id_2: customfield_16924
  vulnerability_id_3: customfield_16925
  vulnerability_id_4: customfield_16926
  vulnerability_id_5: customfield_16927
  triage_status: customfield_16929
  scan_id: customfield_16802
  justification: customfield_13802
  branch_name: customfield_16507
  project_name: customfield_16501
  github_org: customfield_16500
  vulnerability_name: customfield_16505
  package_name: customfield_16803
  vulnerability: customfield_16805
  result_category: customfield_16805
subtask:
  sast: "Sub-task"
  sca: "Sub-task"
  csec: "Sub-task"
  dast: "Sub-task"
default_placeholder:
  justification_default: 'Please Input Justification'
  triage_status_default: 'Please select value'