name: Update Jira Ticket

on:
  workflow_dispatch:
    inputs:
      jira_issue:
        description: "Jira Issue ID"
        default: ''
        type: string
      scan_engine:
        description: "Scan Engine Type"
        default: ''
        type: string

jobs:
  update-jira-ticket:
    runs-on: ubuntu-latest

    env:
      CX_TOKEN: ${{ secrets.CX_TOKEN }}
      CX_TENANT_NAME: ${{ vars.CX_TENANT_NAME }}
      CX_TENANT_IAM_URL: ${{ vars.CX_TENANT_IAM_URL }}
      CX_TENANT_URL: ${{ vars.CX_TENANT_URL }}
      JIRA_PAT: ${{ secrets.JIRA_PAT }}
      JIRA_PROJECT_ID: ${{ vars.JIRA_PROJECT_ID }}
      JIRA_URL: ${{ vars.JIRA_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Jira Script
        run: |
          python3 appsec_triage_main.py \
            "${{ github.event.inputs.jira_issue }}" \
            "${{ github.event.inputs.scan_engine }}" \
